### ISSUE TITLE
Nessus Parser Misses Ports

### ISSUE THREAD

**Issue by mthbrown** [sensepost/gowitness#171]
**Describe the bug**
While using the *nessus* parser, I noticed that it missed a `www` service. I had 2 `www` in my `.nessus` file. It detected one while missing the other

**To Reproduce**

1. Perform a *Basic Network Scan* in Nessus
2. Run:

```
gowitness nessus --file report.nessus
```

**Expected behavior**
It should have detected both of them

**Version Information:**
 - OS: Fedora Linux 36
 - gowitness:

```
$ gowitness version
gowitness: 2.4.2

git hash: c9c6b17
go version: go1.19_linux/amd64
````

**Additional context**

```xml
$ grep -i "www" report.nessus

<ReportItem port="80" svc_name="www" protocol="tcp" severity="0" pluginID="10107" pluginName="HTTP Server Type and Version" pluginFamily="Web Servers">
<ReportItem port="11127" svc_name="www" protocol="tcp" severity="0" pluginID="22964" pluginName="Service Detection" pluginFamily="Service detection">
```

The full report is available [here](https://gist.github.com/mthbrown/973e802d383905a4452f2ce9ce22796c/raw/591650242cf173ca8d8cad63c6fe63136e820251/report.nessus)

**Comment by catpipeless** [comment]
I have this issue as well. I believe it is due to the plugin name not being "Service Detection" possibly an issue with the plugin output as well. I cannot get gowitness to respect the replacement command arguments I provide though.

**Comment by leonjza** [comment]
This is interesting. We're filtering based on the [service name](https://github.com/sensepost/gowitness/blob/2.5.0/cmd/nessus.go#L231) passed through as an option that defaults to [`www` and `https`](https://github.com/sensepost/gowitness/blob/2.5.0/cmd/nessus.go#L126). I'd need to test this to debug what is happening.

**Comment by catpipeless** [comment]
I changed a bunch of the plugin names in the xml to "Service Detection" and got it to work more but not completely

**Comment by quentinpraz** [comment]
I'm facing the same issue. I did some troubleshooting and the parsing seems to be OK. With the _--debug_ option, I can see that all ports are parsed (thanks to [this debug line](https://github.com/sensepost/gowitness/blob/d367079070867b9f230de7e6e141b4e30ea85b9f/cmd/nessus.go#L243C8-L243C8)). 
However, I think that there is an issue when the _ip:port_ are added to the target list [[here](https://github.com/sensepost/gowitness/blob/d367079070867b9f230de7e6e141b4e30ea85b9f/cmd/nessus.go#L240C8-L240C8)]. I'm not proficient in Go but I think that if an IP has multiple open ports, only the latest port will be stored in the target list (others will be overwritten because the map can only have one value pre key).
I'm not able to propose a pull request (du to my poor level in Go) but I hope this could help resolve the issue.
