### ISSUE TITLE
Can I import this project as a library ?

### ISSUE THREAD

**Issue by EduardoRMello** [sensepost/gowitness#197]
Can I use this project as a lib into my golang project ?
Do you have any example ?

**Comment by leonjza** [comment]
You can [import any part of a remote package](https://go.dev/doc/code#ImportingRemote) (with some exceptions), meaning you can import anything in the gowitness project.

That said, currently `gowitness` is not a well structured Golang project, yet. Believe it or not, I started work very recently on v3 and one of the goals is to restructure the project specifically so that it can be used as a library in other code. I'll make sure to have some examples on how to use it as well too.

If you are curious, watch for the `v3` branch in this repo when I commit the first changes to see how it comes along.

**Comment by leonjza** [comment]
After I've rewritten basically everything for v3, this was a key design goal as well. Finally, the answer is yes. I'm yet to write docs on how, but to give you an idea how it would look, check the below example.

You need a driver (chromedp/go-rod, they should be good to use already), a reader (which will just be me pushing stuff into the `Targets` channel now, but you can define some cool stuff here), and finally a writer (I'll use the json lines one I already built here).

```go
package main

import (
	"log/slog"

	"github.com/sensepost/gowitness/pkg/runner"
	driver "github.com/sensepost/gowitness/pkg/runner/drivers"
	"github.com/sensepost/gowitness/pkg/writers"
)

func main() {

	logger := slog.Default()

	// define scan/chrome/logging etc. options. drivers, scanners and writers use these.
	// it includes concurrency options, where to save screenshots and more.
	opts := runner.NewDefaultOptions()
	// set any opts you want, or start from scratch with &runner.Options{}

	// get the driver, the writer and a runner that glues it all together
	driver, _ := driver.NewChromedp(logger, *opts)
	writer, _ := writers.NewJsonWriter("results.jsonl")
	runner, _ := runner.NewRunner(logger, driver, *opts, []writers.Writer{writer})

	// with the runner up, you have runner.Targets which is a channel you can write targets to.
	// write from a goroutine, as the runner's Run()  method will wait for the `Target` channel to close.

	// target "pusher" goroutine
	go func() {
		runner.Targets <- "https://sensepost.com"
		close(runner.Targets)
	}()

	// finally, run the runner, when done, close it
	runner.Run() // will block until runner.Targets is closed
	runner.Close()
}

```
